server:
  port: 8088

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/secondary_db
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: calculator-service
jwt:
  access:
    token:
      expiry: 6000000
      secret:
        key: 357638792F423F4528482B4D6250655368566D597133743677397A24432646294A404E635266546A576E5A7234753778214125442A472D4B6150645367566B58
  refresh:
    token:
      expiry: 864000000
      secret:
        key: 7134743777217A25432A462D4A614E645267556B58703272357538782F413F44

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
